In [1]:

import tensorflow as tf
from model import build_model
import load_data
import random
import os

import numpy as np
from skimage import data, io
import matplotlib.pyplot as plt

SEED = 42
# for reproducability
def reset_random():
  os.environ['PYTHONHASHSEED'] = str(SEED)
  np.random.seed(SEED)
  tf.random.set_seed(SEED)
  random.seed(SEED)
reset_random()

In [2]:
input_dims = 32
(train_data, val_data, test_data) = load_data.load_data_gen(input_dims, seed=SEED)
len(train_data.class_indices.keys())

Found 4800 images belonging to 4 classes.
Found 4800 images belonging to 4 classes.
Found 4800 images belonging to 4 classes.


4

In [10]:
train_data

In [12]:
for data_batch, labels_batch in train_data:
    print('data batch shape:', data_batch.shape)
    print('labels batch shape:', labels_batch.shape)
    print(labels_batch)
    break

data batch shape: (32, 32, 32, 1)
labels batch shape: (32, 4)
[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


In [13]:
model = build_model(input_dims=input_dims, n_clases=len(train_data.class_indices.keys()))
model.compile(optimizer='adam',
              loss=tf.keras.losses.CategoricalCrossentropy(),
              metrics=['accuracy'])
model.summary()

Model: "VGG-liter"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
rescaling_1 (Rescaling)      (None, 32, 32, 1)         0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 32, 32, 32)        320       
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 32, 32, 32)        9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 16, 16, 32)        0         
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 16, 16, 64)        18496     
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 16, 16, 64)        36928     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 8, 8, 64)          0 

In [ ]:
# callback = tf.keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=10)
epochs=100
history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=epochs,
    # callbacks=[callback]
)

Epoch 1/100
150/150 [==============================] - 15s 96ms/step - loss: 8.4284 - accuracy: 0.2590 - val_loss: 8.4060 - val_accuracy: 0.2500

In [10]:
train_data
